#!/bin/bash

export EC2_HOME=/opt/ec2-api-tools
export PATH=$EC2_HOME/bin:$PATH
export AWS_ACCESS_KEY=XXXXXXXXXXXXXXXX
export AWS_SECRET_KEY=XXXXXXXXXXXXXXXXXXXXXXXXX
export JAVA_HOME=/usr
#export EC2_URL_EU=https://ec2.eu-west-1.amazonaws.com
#export EC2_URL_US_E=https://ec2.us-east-1.amazonaws.com
